Repository sainiharit/helloworld, pull requests merged in 2021-10, with the labels that each got.

#3 chronology of classes updated
  css/style.css
Labels: hacktoberfest-accepted

#2 Steallar function added
  js/main.js
Labels: hacktoberfest-accepted

#1 buisness class added
  js/bootstrap.min.js
Labels: hacktoberfest-accepted

#6 animated class added
  css/animate.css
Labels: hacktoberfest-accepted

#14 Update jquery.min.js
  js/jquery.min.js
Labels: hacktoberfest-accepted

#13 Update main.js
  js/main.js
Labels: hacktoberfest-accepted

#12 Update index.html
  index.html
Labels: hacktoberfest-accepted

#10 Update style.css
  css/style.css
Labels: hacktoberfest-accepted

#9 style css update
  css/style.css
Labels: hacktoberfest-accepted

#8 Update style.css
  css/style.css
Labels: hacktoberfest-accepted

#7 Update main.js
  js/main.js
Labels: hacktoberfest-accepted

#19 Update bootstrap.min.css
  css/bootstrap.min.css
Labels: good first issue, hacktoberfest-accepted

#18 Update owl.carousel.min.css
  css/owl.carousel.min.css
Labels: good first issue, hacktoberfest-accepted

#17 Update style.css
  css/style.css
Labels: good first issue, hacktoberfest-accepted

#16 Update style.css
  css/style.css
Labels: good first issue, hacktoberfest-accepted

#15 Update index.html
  index.html
Labels: good first issue, hacktoberfest-accepted

#28 Delete fonts/ionicons directory
  fonts/ionicons/css/_ionicons.scss
  fonts/ionicons/css/ionicons.min.css
  fonts/ionicons/fonts/.DS_Store
  fonts/ionicons/fonts/ionicons.eot
  fonts/ionicons/fonts/ionicons.svg
  fonts/ionicons/fonts/ionicons.ttf
  fonts/ionicons/fonts/ionicons.woff
  fonts/ionicons/fonts/ionicons.woff2
Labels: good first issue, hacktoberfest-accepted

#27 Update index.html
  index.html
Labels: duplicate, hacktoberfest-accepted

#26 Update main.js
  js/main.js
Labels: duplicate, hacktoberfest-accepted

#23 Update index.html
  index.html
Labels: hacktoberfest-accepted

#21 Update style.css
  css/style.css
Labels: duplicate, hacktoberfest-accepted
