Repository sainiharit/helloworld, pull requests merged in 2022-10, with the labels that each got.

#32 HTML Code beautified
  index.html
Labels: help wanted, hacktoberfest-accepted

#31 Create bootstrap.min.js.map
  js/bootstrap.min.js.map
Labels: enhancement, help wanted, hacktoberfest-accepted

#30 Upgraded to latest version
  css/bootstrap.min.css
Labels: help wanted, hacktoberfest-accepted

#29 Upgraded to Latest Version - 5.0
  js/bootstrap.min.js
Labels: documentation, enhancement, hacktoberfest-accepted

#36 Delete ajax-loader.gif
  css/ajax-loader.gif
Labels: enhancement, hacktoberfest-accepted

#35 Update style.css
  css/style.css
Labels: good first issue, hacktoberfest-accepted

#34 Update main.js
  js/main.js
Labels: good first issue, hacktoberfest-accepted

#33 Update jquery.min.js
  js/jquery.min.js
Labels: hacktoberfest-accepted

#41 Update style.scss
  scss/style.scss
Labels: hacktoberfest-accepted

#38 Delete pe03MImSLYBIv1o4X1M8cc8aBc5tU1E.woff2
  pe03MImSLYBIv1o4X1M8cc8aBc5tU1E.woff2
Labels: hacktoberfest-accepted

#37 Delete prepros-6.config
  prepros-6.config
Labels: hacktoberfest-accepted

#45 Delete flaticon.css
  css/flaticon.css
Labels: enhancement, good first issue, hacktoberfest-accepted

#42 Update index.html
  index.html
Labels: enhancement, good first issue, hacktoberfest-accepted

#43 Update aos.css
  css/aos.css
Labels: enhancement, good first issue, hacktoberfest-accepted

#44 Update magnific-popup.css
  css/magnific-popup.css
Labels: enhancement, good first issue, hacktoberfest-accepted
